#+Title: District-level male medical and traditional circumcision
#+Title: coverage and unmet need in sub-Saharan Africa
#+date: 30th March 2023
#+options: toc:nil num:t d:nil author:nil num:nil
#+startup: latexpreview

* Abstract
** Background
In 2016, UNAIDS developed a Fast-Track strategy that targeted 90\% coverage
male circumcision (MC) among men aged 10-29 years by 2021 in priority countries in sub-Saharan 
Africa (SSA) to reduce HIV incidence. There is substantial variation across subnational 
regions within countries in both traditional male circumcision (TMC) practices and progress
towards implementation of voluntary medical male circumcision (VMMC). Tracking progress and
remaining gaps towards VMMC HIV prevention targets requires detailed district-level circumcision coverage data.

** Methods

We analysed self-reported data on male circumcision from 120 nationally representative household
surveys conducted in 33 SSA countries between 2006-2020. A spatio-temporal Bayesian
competing-risks time-to-event model was used to estimate rates of traditional and medical
circumcision by age, location, and time. Several model specifications and calibrations were compared with both in-sample and out-of-sample (OOS) validations. Circumcision coverage in 2020 was projected assuming continuation of estimated age-specific rates, with probabilistic uncertainty. An R package was developed to improve the reproducibility of this analysis. 

** Results
Across 33 countries, from 2010 to 2020 an estimated x million men (x\% CI x-x million)
were newly circumcised, of whom x million (x - x million) were medically circumcised, and
x million (x - x million) traditionally circumcised. In 2020, MC coverage among men 10-29
years ranged from x\% (x\% - x\%) in Zimbabwe (?) to x\% (x\%-x\%) in Togo. MMC coverage
ranged from x\% (x\%-x\%) in Malawi to x\% (x\%-x\%) in Tanzania, and TMC coverage
from x\% (x\%-x\%) in Eswatini to x\% (x\%-x\%) in Ethiopia. The largest increase in MMC
coverage was in Lesotho from x\% to x\%. Within countries, the median difference in MC
coverage between the districts with lowest and highest coverage was x\%, with the smallest
variation in Eswatini (x\% to x\%) and largest in Zambia (x\% to x\%). x million men aged
10-29 need to be circumcised to reach 90\% coverage in all countries. By 2020, x countries
achieved their 90% circumcision coverage target. 

** Conclusions
VMMC programmes have made substantial, but uneven, progress towards male circumcision targets. Granular district and age-stratified data provide information for focusing further programme implementation.


* Background

- Section on HIV in SSA
- Section on circumcision (VMMC reduces male to female incidence by 60%, targets set by UNAIDS, etc)
- Section on existing efforts to estimate circumcision (Cork model, DMPPT2, threemc developed by
  Matthew Thomas, and how it aims to be an improvement (stratified by age, can use survey and programme data, doesn't group by region like Cork, etc))

*** Research Questions

There were several key research questions which we hoped to answer with this analysis:

1. How does total, medical and traditional circumcision coverage vary subnationally across the SSA region? How has this changed over time? 

Result: Broadly speaking, WCA has much higher circumcision coverage, in line with greater cultural practice of TMC associated with these countries, while in ESA TMC and MC coverage is much lower, although this varies quite a lot, both nationally and sub-nationally. 

Figure 2: Map plot
caption:
Figure x: Estimated percentage of men aged 10-29 years who were circumcised sub-nationally in 33 SSA countries. Missing from map: Guinea-Bissau, Equitorial Guinea, Central African Republic and Botswana
Another useful figure here: plot of district level MC coverage coloured by ESA/WCA and size given by population of each
Caption:
Figure x: District-level median percentage of men aged 10-29 years who were circumcised in 2020 in 33 SSA countries. Each point is a district, sized by district population relative to average district size and coloured by the African region their country falls under (Eastern and Southern Africa (ESA) and Western and Central Africa (WCA), respectively). Each white dot represents the national median. A vertical dotted line signifies the UNAIDS target of 90% national MC.

Also should fit in somewhere: geofaceted plot showing differences in TMC/MMC type coverage
2010-2020
Caption:
Figure x: Percentage of men aged 10-29 years who were medically circumcised and traditionally circumcised over time between 2010 and 2020. The horizontal grey dashed line indicates the 90% circumcision coverage by 2021 target established by the UNAIDS Fast Track strategy. The lighter shaded area represents projection after the most recent household survey. Purple areas represent countries where circumcision type could not be ascertained from surveys.

2. How have subnational patterns in circumcision coverage vary across different ages and age groups? 

Result: A circumcised individual is much more likely to have undergone MMC for progressively younger ages, while the converse is true for TMC. (I wonder why this isn't untrue for paediatric TMCs in VMMC countries? Surely TMCs should be higher than MMCs for these ages, at least in VMMC countries?) 

Figure: Geofaceted plot, but by age rather than year, for 2020 (doesn't look too bad, ask Jeff what he thinks)
Caption:
Figure x: Projected percentage of men from 0 to 60 years old who were medically circumcised and traditionally circumcised by 2020. The horizontal grey dashed line indicates the 90% circumcision coverage by 2021 target established by the UNAIDS Fast Track strategy. Purple areas represent countries where circumcision type could not be ascertained from surveys.

3. Has TMC decreased, both in response to VMMC programme implementation in target countries, and more generally across the entire SSA region? 

TMC has decreased in VMMC target countries, presumably largely due to the implementation of VMMC programs in districts which traditionally practised TMC. It has also, interestingly, declined (with a lot of variability) in non-VMMC countries, possibly in response to general economic upliftment and development in these countries. 

Plot for this? Can just refer to previous figures perhaps? Or perhaps a table is best?

4. How have efforts to meet UNAIDS goals in VMMC target countries progressed? If these targets have not been met, how many additional circumcisions are required to meet these goals? 

Result: Kenya (and maybe Mozambique?) is the only country expected to have reached the VMMC target of 90% circumcision coverage amongst 10-29 year olds by 2020. In other VMMC countries, significant progress towards this goal has been made, but there still remain a significant number of un-circumised 10-29 year olds. 

Figure: Geofaceted plot showing circumcision coverage increase over time (could do for several of the larger age groups with their associated targets as dashed lines)
However, probably only interested in VMMC countries here, so table probably more appropriate
Additional Figure: Some kind of table showing progress towards goals?

5. How do our results compare to those of the DMPPT2 model? 

Result: In many VMMC countries, threemc results and DMPPT2 results largely agree. However, for several countries, such as Tanzania, Zimbabwe and parts of Kenya, we can see that DMPPT2 estimates far exceed empirical survey and threemc estimates, and indeed the population of many districts, suggesting that they may be adversely affected by (i) people travelling from their home districts to others to avail of VMMC programmes, and (ii) possible misreporting occurring in programmatic data due to incentives to report higher numbers of circumcisions for VMMC clinics. 

Figure: (For appendix): comparisons between DMPPT2 results, survey estimates and threemc results
Merely reference these figures in this section

* +Data+ (moved to methods)                                          :noexport:

- Anything on shapefiles and area boundary classification needed?
#+begin_comment
Jeff: Just the source (referencing UNAIDS) and definition that we use 'health districts'
#+end_comment

** Surveys

- 120 household surveys conducted in 33 SSA countries 2002-2019
- Self-reported circumcision:
  - Status (MC vs uncircumcised),
  - Type (MMC vs TMC),
  - Year, and
  - Age 
recorded.
- Major survey series (DHS, AIS, PHIA, MICS, HSRC in ZAF)
- Individual-level data: self-reported circumcision status by male respondents
- Respondents located to districts using masked cluster geocoordinates
- Located to admin 1 (province) where coordinates not available (MICS)
  +VMMC programme data not used+
#+begin_comment
Jeff: "VMMC programme data not used" is a point for introduction or discussion
#+end_comment
  

- Circumcisions performed by a medical professional and/or in a medical setting are categorised as MMC. Otherwise, circumcisions are TMC. Where no data is present on location or provider, circumcision type is treated as "Missing".
  Note: Can I use Jeff's images of DHS and PHIA survey questions in presentations?
  Would be useful in explaining this point. 
#+begin_comment
Jeff: In appendix: put section describing the classification and include the specific question text (from those screenshots) and description of how they were each classified.
#+end_comment

- Individual-level household survey data provide direct estimates of circumcision rates over time and by type for years preceding survey.

- Direct estimates of TMC practices, age at circumcision, VMMC impact

- Also include participation rates from surveys.

- Figure: Figure from poster with surveys of each provider for each country, caption:
  "Figure 1: Household surveys detailing circumcision patterns in SSA. The colour and size of points are determined by the provider and sample size of each respective survey. Triangular points have no information on circumcision type."

** Populations

- Sub-national populations from WorldPop (reference) (also are they all from WorldPop??)

* Methods

- Something on calculating survey estimates for circumcision coverage? Perhaps Jeff could write
  this. 

** Data  
Anything on shapefiles and area boundary classification needed?  

*** Surveys  

120 household surveys conducted in 33 SSA countries 2002-2019  
Self-reported circumcision:  
Status (MC vs uncircumcised),  
Type (MMC vs TMC),  
Year, and
Age  recorded.  

Major survey series (DHS, AIS, PHIA, MICS, HSRC in ZAF)  

Individual-level data: self-reported circumcision status by male respondents  

Respondents located to districts using masked cluster geocoordinates  

Located to admin 1 (province) where coordinates not available (MICS)  

VMMC programme data not used  

Circumcisions performed by a medical professional and/or in a medical setting are categorised as MMC. Otherwise, circumcisions are TMC. Where no data is present on location or provider, circumcision type is treated as "Missing". Note: Can I use Jeff's images of DHS and PHIA survey questions in presentations? Would be useful in explaining this point.  

Individual-level household survey data provide direct estimates of circumcision rates over time and by type for years preceding survey.  

Direct estimates of TMC practices, age at circumcision, VMMC impact  

Also include participation rates from surveys.  

Figure: Figure from poster with surveys of each provider for each country, caption: "Figure 1: Household surveys detailing circumcision patterns in SSA. The colour and size of points are determined by the provider and sample size of each respective survey. Triangular points have no information on circumcision type."  

*** Populations  

Sub-national populations from WorldPop (reference) (also are they all from WorldPop??) 

** Model
- Extended threemc developed in Thomas et. al. to model 33 countries. Circumcision rates, incidence and coverage (i.e. cumulative incidence) estimated, with associated 95% uncertainty bounds.
  Countries modelled at the PSNU area level, or the most granular level used in surveys, and poststratifed to produce estimates for "parent" regions. 
  Some changes in the model from the original threemc model include:
  - Allowing for survey results for less granular areas to inform likelihood estimation within model (Matt said he would write an explanation of this, possibly for the Appendix)
  - Allowing for the includsion of a temporal effect for TMC, which was previously assumed to be constant over time in the case of South Africa, but in many countries, particularly in WCA, has been empirically observed from survey estimates to decrease over time (possibly refer to empirical rates plots for TMC in the appendix).
  - Experimenting with different choices of temporal prior, specifically exploring the use of an
    AR1, RW1 and RW2 temporal prior. 

#+begin_comment
Jeff: Here is where we mention no survey data
#+end_comment
   
** +Choice of model specification+ (draft)

Jeff:
- Model selection: particularly interested in  
- (1) Model specification for time trends in TMC and paediatric circumcision -> in sample fit 
- (2) Short-term future projections; ensuring appropriate future uncertainty in all countries
   -> out-of-sample prediction withholding the final survey (and any survey in the one year previous) 

- Choose best model specification (i.e. which terms to include (TMC, paediatric MMC, etc)) for
  each country using within-sample validation.
- Include figures comparing models for each country in appendix, refer to them here.
#+begin_comment
Here describe the method used for the comparison (out of sample prediction process) and
metrics used for comparison. Report the results of the model selection in the appendix.
#+end_comment
- Credible interval coverage, ELPD, CRPS and fit statistics (ME, MSE, RMSE) used to inform
  decision. 



*** (Very!) Rough draft (without figures and conclusions from validations on model choice) (Much of this will probably end up in the appendix)

Qualitatively, we made some presumptions about certain countries and their circumcision patterns.

**** Non-VMMC countries
Firstly, in non-VMMC countries, traditional circumcision likely makes up the bulk of circumcision (or at least has done historically).
Therefore, most medical circumcisions in these countries will likely be MMC-T, and so likely also be performed on paediatric individuals in traditional settings.
Also, because much of MMC performed in non-VMMC countries will be as a result of converting TMC to MMC-T, the assumption that traditional circumcision rates in these countries have been relatively constant is likely inaccurate.
Instead, it is likely that circumcision patterns have undergone a generational change as a result of general development in their countries (could definitely say this better). As such, a time effect for TMC in non-VMMC countries is very important for accurately modelling and understanding their circumcision patterns, particularly in how the relative makeup of M
(Note: would be a good idea to look into surveys for these countries to see if this checks out! I.e. for non-VMMC and VMMC surveys, it might be a good idea to compare the number of people with different circumcision types for location and provider,  to substantiate this assumption)

**** VMMC countries
For VMMC countries, changes (i.e. increases) in circumcision have, naturally, been driven by the VMMC programmes themselves in these countries.
As such, we can be confident that MMC of paediatric individuals is minimal, in line with UNAIDS VMMC policies (reference, word better, probably too confident!), and so we assume a constant rate of paedaitric MMC over time, that is to say, none.
TMC is slightly more complicated.
In some VMMC countries TMC appears to have stayed relatively stable, while in others, particularly Mozambique and Zambia (any more? Could show map of negative changes in TMC), MMC-T, i.e. conversion of MMC to TMC, appears to have occured (again, word better?)
Rather than treating each VMMC countries' TMC rate on an individual basis, merely for the sake of a slightly more parsimonious process model and a less computationally expensive modelling process, we decided it was much simpler to allow TMC to vary over time, as we have done for non-VMMC countries. 

We have also performed a quantitative analysis on how the choice of including a constant paediatric MMC rate and a constant TMC rate effect the fit of our model, by looking at the within-sample posterior predictive distribution and some error statistics associated with this distribution when compared to our survey estimates of circumcision coverage. (...?)

** +Model Calibration and choice of temporal prior+ (draft)          :noexport:

- Calibrated MMC-related variance hyperparameters using grid search. Idea is to use information
  from countries with more surveys to inform variance (which was suspected to be underestimated)
  in countries with fewer surveys, analagous to using a model with partial pooling for each
  country in the Sub-Saharan region, which would be much too computationally expensive to fit. 

*** Another very rough draft  (not sure if everything here is appropriate for this section) (much of this will probably go to the appendix as well!)

For some VMMC priority countries, we do not have access to more recent survey data. 
One particular country where this is the case is Tanzania, whose most recent survey is a 2016 PHIA survey.
In these circumstances, VMMC programme data is an available source of more recent data.
The DMPPT2 model explicitly uses this data to estimate MMC. 
+Putting aside suspected problems associated with the programme data, such as individuals availing of VMMC in districts in which they are not residents, and suspected reporting biases with countries like TZA and Zimbabwe,+ the results of DMPPT2, particularly at the national level, where travel between districts is ignored, suggest that VMMC may have scaled up at a rate not anticipated by threemc where only these older surveys are available. 
+This is consistent with the out-of-sample (OOS) evaluations of our model fit to countries like ZWE, where removing access to the most recent (2018 DHS) survey similarly+
+underestimates VMMC scale up (include plot here?).+
Hence, we feel that our model likely underestimates it's own uncertainty with regards to predicting circumcision coverage for progressively later years than our last
available surveys, particularly in the case of VMMC priority countries which started with a low circumcision coverage. What we desire is a more dramatic "fanning" out of
our prediction interval as we forecast further from the last available survey data, again, particularly for VMMC countries in which there may have been a large scale up
in circumcision coverage since the last available survey, representing an intervention via VMMC programmes which our model, fit for each country separately, is not equipped to
handle.

Due to computational constraints, we cannot model each country together as one singular area hierarchy, which, through the neighbourhood correlation structure inherent in the model,
would allow the model to borrow information from countries with a large amount of available data to inform predictions in countries with older and/or fewer surveys (i.e. some partial pooling
between countries would take place).
One alternative to using a partially-pooled model is to use the uncertainty estimates which produce the best predictions for countries with more recent data to inform our uncertainty estimates in countries with less recent survey data available. 

To quantitatively explore this hypothesis, we performed an out of survey (OOS) evaluation of the model fit to each country, removing their most recent survey data and comparing posterior predictions to the survey-estimated circumcision coverage. 
(Something about this incorporating survey design/effective sample sizes etc should probably be here)
These comparisons consisted of comparisons of mean predictions, using ELPD and CRPS scores, as well as error statistics such as the ME, RME and RMSE, and evaluations of the
"calibration" of our model with regards to it's posterior predictive uncertainty for each unique region-year-age-type (what does Matt use for this) stratum of our data. 

This involved comparing survey estimates of circumcision coverage with the 50%, 80% and 95% credible intervals (CI) coverage of our posterior predictive distribution. A "good" calibration
was regarded as one in which roughly 50% of (training) survey observations fell within the 50% CI range, 85% within the 85% CI range, and 95% within the 95% range.

Two principal components of the model largely determine how the uncertainty of our model predicitions scale up over time: 
1. *The choice of temporal prior*: threemc uses an AR 1 temporal prior. However, this is easily sable with, for example, a random walk (RW) prior. These temporal priors
   differ consireably in how they use previous estimates to inform future predictions, and so we appraised a number of choices for our temporal prior to determine if there
   was a preferable alternative to our default AR 1 temporal prior, with regards to the particular context of increasing year-on-year uncertainty bounds.
   The choice of temporal prior was included in this OOS analysis, rather than in our
   previous within-sample parameter chioce, as the main effect of the temporal prior is in
   determining our temporal forecast. As such, an OOS validation would prove to be more informative in determining the optimal temporal prior for the largest number of countries. 
2. *The choice of (log) variance hyperparameters*: The "unpooled" optimised time-related variance hyperparameters for each respective country varied significantly, but in general certain patterns and values for these hyperparameters could be associated with a greater "fanning" out of our uncertainty bounds for successive prediction years.

/For the AR 1 model, the effect of different time correlation parameters on our uncertainty bounds was determined to be minimal, and in the interests of parsimony, these parameters were/
/ignored in our calibration efforts with this model/ ()

** +threemc+ (can just have in small code availability section at the end)

+- Section on development of threemc package, which allows for much of this analysis based on freely available survey data to be reproduced.+
+- Also used `orderly` (link to threemc-orderly) and `didehpc` for much of this work.+

#+begin_comment
Jeff: Can just include a sentence that the package exists in ‘Code availability’ section at
end
#+end_comment

* Results

- First section: summary descriptive statistics about the data 
- Should I have a section on results of model choice and calibration here first?  
#+begin_comment
Yes; 1-2 paragraphs summarising the key decisions. Then referring to appendix for tables and details.
#+end_comment
- Will I need a section for each country in my results? Or can I just include plots for
  each in the appendix  
- Will probably need some kind of table summarising coverage in different countries  
- Will I need something on comparison to survey points and/or DMPPT2 results?  

** Data (Better title than this?)

** Spatio-temporal trends in Circumcision Coverage in Sub-Saharan Africa

Figure: Map plots of MC, MMC and TMC coverage for 10-29 year olds from 2010 to 2020,
including change (as in poster & various presentations)

Additional Figure: Geo-faceted plot including MC estimates (split by colour between MMC & TMC)
for each country from 2010 to 2020. 

*Note: not showing much age variability in these plots!*

Include:
- Number of (MC/MMC/TMC) circumcisions performed in SSA from 2010-2020
- Increase in overall circumcision coverage across region 2010-2020
- Largest increase in coverage was in country x
- Something about decrease in TMC observed in several countries (particularly non-VMMC), where
  has this been greatest?
#+begin_comment
Jeff: I would make a separate research question/subheading about changes in TMC over time
#+end_comment

** Sub-national Spatial Variability

Figure: Plot showing sub-national variation in circumcision coverage in each country from
poster

- Substantial sub-national variation in circumcision coverage, particularly for ESA countries. 
- Within countries, the median difference in MC coverage between the districts with the lowest
  and highest covreage was x%
- x% in ESA compared to x% in WCA
- Lowest in country x, highest in country x
- MC/TMC/MMC coverage in 2020 ranged from x%(x% - x%) in ? to ...
- Number of districts achieving 90% MC target, highest and lowest country

** Variability in Age at Circumcision

Figure: Distribution of age at circumcision for different countries

- Talk about patterns in TMC (usually either neonatal or as part of TMIC), how MMC is usually
  younger in non-VMMC countries (being MMC-T) than VMMC countries (largely MMC-nT). 

- Could also have another geofaceted plot, but this time with age on the x-axis, rather than year?
  Concerned I'm not including enough about age-related variability here! 

- What figures (i.e. numbers) to include here? Haven't talked much about age variability in
  coverage in previous presentations etc ...
  
** Progress towards UNAIDS Targets in VMMC countries

#+begin_comment
Jeff: In this section, show those circumcision by age plots
#+end_comment

Figure: Table of MC, MMC and TMC coverage for VMMC countries for 10-29 year olds in 2020

- Number of countries which reached UNAIDS targets (likely none)
- Number of circumcisions performed in VMMC countries from 2010-2020
- Number of additional circumcisions required to reach goal
- "This belies large subnational variation, with x% (x-x%) of priority country districts estimated to have achieved x% MC by 2020" 

** Comparison with DMPPT2?

* Discussion

- Similar, more fleshed-out section to what is in appendix. 
Dichotomy in circumcision practices between WCA and ECA: in coverage, type of circumcision, and age at circumcision 
WCA: generally high everywhere; in ESA: lot of subnational variation 
Within WCA: quite a lot of variation in circumcision type between countries  
Transition from MMC -> TMC independent of VMMC for HIV programmes — enumerate countries where we see this 
Comments on challenges and limitations of interpreting these results (projections without recent programme data) vs. challenges of interpreting VMMC programme data  
Comments on circumcision < age 15. 



** Limitations
- Computational constraints meant we could not include a spacetime interaction effect for TMC, and
  also means we were forced to calibrate our model in the method described above, rather than performing a partially pooled model for the entire SSA region.
- Of threemc: If number of circumcisions increases (such as when population increases), this may
    cause TMCs to increase, when they're supposed to stay constant or decrease. 
- More!

** Challenges:
- Inconsistent MC self-reporting by same cohort in successive surveys, e.g. in 2017 survey, men
    30-34 report higher % circumcised in 2012 than ‘same’ men age 25-29 in 2012 survey.
    Affects circumcision level, and distribution by type.
- ‘Replacement’ of traditional circumcision by medical circumcision.
  Evidence of this in surveys from several countries; work in progres.
  +Also not fully accounted for in DMPPT2 baseline coverage inputs+
- In some cases, survey providers report different coverage (such as in Lesotho and Uganda for DHS and PHIA)
- Surveys imply different level of scale-up than programme data for several countries,
  with surveys suggesting fewer VMMCs conducted than programme data.
  This raises interesting questions about the differences between survey and programmatic estimates. 
  Possibly suggests biases in programme data. 
- Some countries have only one usable survey available, providing less data to the model and for
  our out-of-sample validations. 
  - More!

* Appendix

Include (non-exhaustively):
- Table of surveys
- Empirical rates plots from each survey
- Methods section about threemc (think Matt is going to write this)
- Plots for choice of model specification:
  - Comparing different model specifications for each country, plotting coverage against time
    and age group, respectively
- Plots for model calibration and choice of temporal prior:
  - Calibration plots: Boxplots (and/or violin plots?), possibly 3D plots such as 3d dot plot  and/or ternary plot
- Country-specific plots from Matt's paper
- Country-specific comparison plots to survey and DMPPT2 results

* Meeting with Jeff on outline 

Paper Outline: 

- Could compare to programmatic data, not just DMPPT2 results (i.e. "x number of circs between 2010 and 2020" can be compared to program data estimates)
  At the last UNAIDS meeting we had something on this, need to ask Katherine about it perhaps?
- In Appendix, copy text in DHS and PHIA surveys, show how medical/traditional circumcision distinction is made from these surveys
- Model selection: particularly interested in the short term future projections, and that informed how we performed model selection
Two choices, include table of comparisons for these models 
- Model selection and calibration: Have brief/high-level summary, include in results (go back to EPP-ASM paper), often seen in GBD papers
  Leave more numerical stuff for appendix
- Include how we also withheld surveys from the year before the last survey year
- Drop mention of MMC-T & MMC-nT, we model this as temporal changes in TMC
- Programme data & DMPPT2 comparisons will be in Discussion
- Just mention that package exists and about code availability as brief note at the end of paper, like in Tim's paper (also mention orderly)
- First section of results should be some summary statistics of the data
- No need for results on each country, we want multi-country results
- At the end of the background section, we want a list of aims/research questions
- Move changes in traditional circumcision to separate section/research question, interesting and novel observation
Can show sment of TMC by MMC, that's fine. 
- Progress towards VMMC targets may be covered 
- Would be nice to show uncircumcised populations by age ("age pyramid" plot), maybe with VMMC targets

Aim to have a table with a summary 
Might be nice to include range and coefficent across districts

- Discussion: 
- Have geofaceted plot (or at least *something on rates*!!) for medical and traditional circumcsiion
- See Jeff's notes on discussion
- For paper figures, want to have an idea
- *For the questions I want to answer in this paper, what are our findings?*
- What is important for the reader to know about that (e.g. broad patterns in survey comparisons)?
- In model selection, mention briefly about coverage stats etc
  
*Put research questions in, mock up figures and tables*

ETH: Fit to just Addis and see how that goes!

Calibration: 
Doesn't like 3D dotplot, really likes ternary plot, if I can just work out the details!

Questions: 
- Tim said that scaling year often helps in modelling (particularly in TMB), should we be doing that?
  
Aim to check in Tuesday/Wednesday before I head off
Consolidate where we're at before holiday!

